### ISSUE TITLE
Extra comma issue

### ISSUE THREAD

**Issue by nolandubeau** [strongloop/loopback-sdk-angular-cli#17]
Hello,

I'm using the latest version of the CLI and as well as the storage containers model.  linting reported the following extra comma error:  

see:  <<<<<<<<<<<<

```js
 /**
         * @ngdoc method
         * @name lbServices.Container#download
         * @methodOf lbServices.Container
         *
         * @description
         *
         * <em>
         * (The remote method definition does not provide any description.)
         * </em>
         *
         * @param {Object=} parameters Request parameters.
         *
         *  - `container` – `{string=}` - 
         *
         *  - `file` – `{string=}` - 
         *
         *  - `res` – `{object=}` - 
         *
         * @param {function(Object,Object)=} successCb
         *   Success callback with two arguments: `value`, `responseHeaders`.
         *
         * @param {function(Object)=} errorCb Error callback with one argument:
         *   `httpResponse`.
         *
         * @returns {Object} An empty reference that will be
         *   populated with the actual data once the response is returned
         *   from the server.
         *
         * This method returns no data.
         */
        "download": {
          url: urlBase + "/containers/:container/download/:file",
          method: "GET"
        }, // <<<<<<<<<<<<  trailing comma
      }
    );
```

**Comment by bajtos** [comment]
Thank you for the report. Is this causing you a real problem, e.g in IE8?  In general, it is more important for us to keep the code generator simple, than to make the output pass the linter. So unless there is a real problem in a browser, I'll be very reluctant to fix this.

Related issue: https://github.com/strongloop/loopback-sdk-angular/issues/92

@ru108 you have reported the trailing-comma problem in IE8 as linked above, are you affected by this issue?

**Comment by bajtos** [comment]
As part of our issue triage process, we are closing items that have been inactive for an extended period of time. Feel free to reopen this issue if you can provide any new information to help us with resolving the issue.
