### ISSUE TITLE
error in lb-ng command

### ISSUE THREAD

**Issue by isnraju** [strongloop/loopback-sdk-angular-cli#25]
Hi, I am trying to generate lb-ng services file from command line, it is giving a type error. not sure why this error is coming, previously i was able to generate file from api, I may be doing something small mistake. please gude me. is it complaining about missing node modules or some issue in my server code? or is it a bug in the SDK?

```
vagrant@vagrant-ubuntu-trusty-32:/api$ lb-ng server/server.js client/js/services/lb-services.js -m lbServices -u http://192.168.57.50:3000/api
Loading LoopBack app "/api/server/server.js"
Generating "lbServices" for the API endpoint "http://192.168.57.50:3000/api"
/usr/lib/node_modules/strongloop/node_modules/loopback-sdk-angular-cli/node_modu
les/loopback-sdk-angular/lib/services.js:47
  app.handler('rest').adapter.getClasses().forEach(function(c) {
      ^
TypeError: undefined is not a function
    at describeModels (/usr/lib/node_modules/strongloop/node_modules/loopback-sd
k-angular-cli/node_modules/loopback-sdk-angular/lib/services.js:47:7)
    at Object.generateServices [as services] (/usr/lib/node_modules/strongloop/n
ode_modules/loopback-sdk-angular-cli/node_modules/loopback-sdk-angular/lib/servi
ces.js:31:16)
    at Object.<anonymous> (/usr/lib/node_modules/strongloop/node_modules/loopbac
k-sdk-angular-cli/bin/lb-ng:31:24)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by bajtos** [comment]
Could you please create a small app reproducing the problem using the sandbox project as described on [wiki](https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report)? It's very difficult to tell what's happening on your machine without that.

**Comment by davidcheung** [comment]
@isnraju closing stale issue, please feel free to reopen (would be great if you could [provide steps to reproduce](http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report))
