### ISSUE TITLE
hasMany through relations not created in lb-services

### ISSUE THREAD

**Issue by alexjose** [strongloop/loopback-sdk-angular-cli#26]
I have 3 model `user`, `request` and `donation`. Following the the relations between them.

**user**
```javascript
{
  "name": "user",
  "plural": "user",
  "base": "User",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
"relations": {
    "requests": {
      "type": "hasMany",
      "model": "request",
      "foreignKey": "userId"
    },
    "donations": {
      "type": "hasMany",
      "model": "request",
      "foreignKey": "userId",
      "through": "donation"
    }
  },
...
...
```

**request**
```javascript
{
  "name": "request",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
"relations": {
    "user": {
      "type": "belongsTo",
      "model": "user",
      "foreignKey": "userId"
    },
    "donators": {
      "type": "hasMany",
      "model": "user",
      "foreignKey": "requestId",
      "through": "donation"
    }
  },
...
...
```

**donation**
```javascript
{
  "name": "donation",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "relations": {
    "donator": {
      "type": "belongsTo",
      "model": "user",
      "foreignKey": "userId"
    },
    "request": {
      "type": "belongsTo",
      "model": "request",
      "foreignKey": "requestId"
    }
  },
...
...
```

I created the lb-services using the lb-ng cli too. The service is created with `User.donoations.create()` service but not with `Request.donators.create()`. No services related to Request.donators are created.

**Comment by bajtos** [comment]
This may be a bug in the code generator. Could you please create a small project reproducing the problem per [wiki instructions](https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report)?

**Comment by gustavomick** [comment]
hi bajtos, (sorry about my english) .. it happened same to me. when using "through" property lb-ng doesnt work as expected, but api explorer work just fine. 

as hot fix im trying to use code to add "through" to relations... dont no yet if this will work, nevertheless this bug makes imposible to use "keyThrough" property i think. 

is this issue still alive? 

thank you. 
ref: https://docs.strongloop.com/display/public/LB/HasManyThrough+relations#HasManyThroughrelations-Selfthrough

**Comment by bajtos** [comment]
Hi @gustavomick, thank you for the comment.

This issue is still alive, I am waiting for somebody to provide an example to reproduce the issue (see [wiki instructions](https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report)).

I suspect this will be a bug, but need to check it myself locally and unfortunately I don't have enough time to create the example app myself.

**Comment by gustavomick** [comment]
@bajtos i guess is better to merge this with https://github.com/strongloop/loopback-sdk-angular/issues/187

**Comment by davidcheung** [comment]
>i guess is better to merge this with strongloop/loopback-sdk-angular#187

agreed, closing this issue in favor of strongloop/loopback-sdk-angular#187
