### ISSUE TITLE
ng-annotate breaks generated lbServices

### ISSUE THREAD

**Issue by Evanion** [strongloop/loopback-sdk-angular-cli#29]
There is a diff in the service names and their annotations in the generated angular code:

`````JS
module.factory(
  "User",
  ['LoopBackResource', 'LoopBackAuth', '$injector', function(Resource, LoopBackAuth, $injector) {
    var R = Resource(
      urlBase + "/Users/:id",
      { 'id': '@id' },
      {
/// abbreviated for clarity
`````
The service being called in the function parameter is `Resource`, but it's actual name is `LoopBackResource`.

The annotation will get replaced by ng-annotate when we run our gulp tasks. thus breaking the module, and causing angular to be unable to find the service, since it's looking for `Resource` rather than `LoopBackResource`.

**Comment by bajtos** [comment]
@Evanion thank you for reporting the issue. Could you please contribute a fix yourself?

**Comment by Evanion** [comment]
Yea, I will look into it when I have some free time.

**Comment by luissombra** [comment]
an workaround would be to create a gulp task that replace the word Resource per LoopBackResource. There is a plugin that can do this https://www.npmjs.com/package/gulp-replace.

The task could looks like this:

gulp.task('gen:loopback', function () {
  return gulp.src('../my-path/server/server.js')
    .pipe(loopbackAngular())
    .pipe(rename('lb-services.js'))
    .pipe(replace('Resource,', 'LoopBackResource,'))
    .pipe(replace('Resource(', 'LoopBackResource('))
    .pipe(gulp.dest('./src/app/components'));
});
