### ISSUE TITLE
Fix lb-ng to support async app boot

### ISSUE THREAD

**Issue by doublemarked** [strongloop/loopback-sdk-angular-cli#32]
We recently added a Loopback boot script that is async, by adding the optional 2nd callback parameter. We did this in order to serially execute some async operations that we have taking place during boot.

Once we did this, two things happened,
   1. Our mixins also started loading async.
   2. Our `lb-ng` command no longer generates a correct client lib - it does not wait for the async boot process, so anything that occurs in the async code (including code from our model mixins that initializes relations, etc) does not execute prior to the client lib generating the libraries.

**Comment by davidcheung** [comment]
Hi @doublemarked, Thanks for the pull request, I would like to move the whole conversation over to the Pull request side as it will be easier to track.

**Comment by davidcheung** [comment]
@doublemarked  Actually giving it more thought, I shouldn't have closed the issue, reopening and will close once fix is merged.

**Comment by bajtos** [comment]
This is clearly an oversight on our side, we forgot to update lb-ng after we implemented async boot script.
