### ISSUE TITLE
Loopback API change breaks delete method

### ISSUE THREAD

**Issue by mirow** [strongloop/loopback-sdk-angular-cli#35]
Previously, Loopback delete API returned 204 No Content for all requests, now (in version 2.25.0 at least) it returns 200 OK and an empty array. This causes Angular to throw an error:
"Error in resource configuration for action `deleteById`. Expected response to contain an object but got an array"

See: https://github.com/strongloop/loopback/issues/1322

**Comment by davidcheung** [comment]
Hi @mirow, Sorry for the late reply, is this still an issue for you? I'm actually not able to reproduce your issue. In my test application it doesn't throw errors from the sdk, I have tried both versions of before [this PR](https://github.com/strongloop/loopback/pull/1667) and after
- `v2.22.2`
  -  response http code : 204 
  - no content 
- `v2.25.0`
  - response http code : 200 
  - return : `{count : 1}`

A few things you can check
- Is your controller is dependent of `res` from `model.deleteById` ? 
- Have you tried regenerating the `lb-services.js` with `lb-ng`
- try updating strong-remoting

**Comment by mirow** [comment]
I still have the problem in **one** project, even with loopback@ v2.26.2, but another works fine. 

* loopback@ v2.26.2
  * response http code : 200
  * return : `[]`

In another project the response is correct,  `{count : 1}`. I think it must be because in the problematic project we use a fork of an older version of `loopback-connector-postgresql` (based on 1.6.1 I think). Maybe the connector doesn't return the count? Updating the connector will probably fix this.
