### ISSUE TITLE
Support for Angular2

### ISSUE THREAD

**Issue by mnvx** [strongloop/loopback-sdk-angular-cli#37]
Related with issue on [loopback-sdk-angular](https://github.com/strongloop/loopback-sdk-angular/issues/188) module.

Command line module must be changed too for suporting command format, what proposed [JonnyBGod](https://github.com/strongloop/loopback-sdk-angular/issues/188#issuecomment-175694476)

I think it is good idea to use current format with option `-l` for generation of code for Angular2:

    lb-ng ./server/server.js ./client/src/app/lb-services.ts -l angular2

**Comment by bajtos** [comment]
I think is is no longer relevant, see https://github.com/strongloop/loopback-sdk-angular/issues/188#issuecomment-242075509
