### ISSUE TITLE
Expected response to contain an object but got an array

### ISSUE THREAD

**Issue by narongdejsrn** [strongloop/loopback-sdk-angular-cli#40]
I have 2 models game & salesItem 

game hasMany salesItem, salesItem belongsTo game, which will auto gen /games/:id/salesItem

When I generate and use lb-services.js It says "Expected response to contain an object but got an array" when I try to request to Game.salesItem.findById({id: }).

Currently I managed to temporary fixed by editing the lb-services.js on "::findById::game::salesItem": { section to include isArray: true, but it think its the lb-ng bug?

**Comment by davidcheung** [comment]
sorry for the late reply, 
@narongdejsrn would you be able to provide steps how to reproduce your issue? perhaps in the [loopback-sdk-angular](https://github.com/strongloop/loopback-sdk-angular/issues) repo instead 
http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report 

I'm closing this issue now, please reopen this in [loopback-sdk-angular](https://github.com/strongloop/loopback-sdk-angular/issues)
