### ISSUE TITLE
timeout in generated services for angularjs

### ISSUE THREAD

**Issue by hussainak** [strongloop/loopback-sdk-angular-cli#42]
Hi there,

When I generate AngularJS SDK for my LB API, it generates the following code for each API method (login is an example below)

`"login": {
          params: {
            include: "user"
          },
          interceptor: {
            response: function(response) {
              var accessToken = response.data;
              LoopBackAuth.setUser(accessToken.id, accessToken.userId, accessToken.user);
              LoopBackAuth.rememberMe = response.config.params.rememberMe !== false;
              LoopBackAuth.save();
              return response.resource;
            }
          },
          url: urlBase + "/Members/login",
          method: "POST"
        },`

In an event of a server failure or when server is unreachable, the code never returns a response/error. I believe you need to include timeouts in generated code.
Any thoughts?

**Comment by hussainak** [comment]
@bajtos

**Comment by bajtos** [comment]
Hi, I am not enough familiar with Angular ngResource service to be able to judge this. Isn't there any way how to configure the timeout globally?

**Comment by hussainak** [comment]
Thats exactly what I need
1. There needs to be a provision to include a timeout globally
2. Global timeouts aren't good enough when a long running activity like image upload is occurring, need local timeouts too.

In order to resolve this, the lg-ng generator needs to include timeout in its generated code, currently there is no way except to edit the lb-services.js by hand. For e.g:

`"login": { params: { include: "user" }, interceptor: { response: function(response) { var accessToken = response.data; LoopBackAuth.setUser(accessToken.id, accessToken.userId, accessToken.user); LoopBackAuth.rememberMe = response.config.params.rememberMe !== false; LoopBackAuth.save(); return response.resource; } }, url: urlBase + "/Members/login", method: "POST", timeout:5000 },`

Notice the timeout:5000 after method:POST

**Comment by davidcheung** [comment]
i think sdk-angular might be a better place for this issue, created https://github.com/strongloop/loopback-sdk-angular/issues/249
closing this now
