### ISSUE TITLE
lb-ng and nodemon

### ISSUE THREAD

**Issue by madkoding** [strongloop/loopback-sdk-angular-cli#57]
Using nodemon to check for changes in the model, and regenerate the lb-service file,
in previous versions work fine, but now lb-ng runs another server.js instance

**Comment by davidcheung** [comment]
possibly same issue as #59

**Comment by davidcheung** [comment]
@madkoding can u take a look at #59 to see if reverting to use `process.nextTick` solves your problem? if so then likely its the same issue 
https://github.com/strongloop/loopback-sdk-angular-cli/blob/v2.0.1/bin/lb-ng#L55

**Comment by madkoding** [comment]
confirmed, `process.nextTick` do the work :)

**Comment by davidcheung** [comment]
closing in favor of #59
