### ISSUE TITLE
Support for Loopback with ES6

### ISSUE THREAD

**Issue by rigobcastro** [strongloop/loopback-sdk-angular-cli#69]
When I try to use **lg-nb** command with a loopback es6 server this crashes. I began using loopback with es6 and Babel, it's important generate services for my Angular App from my loopback es6 server.

Thanks!

**Comment by bajtos** [comment]
Hello, how can I reproduce this issue? Please create a small app reproducing the problem - see our [Bug reporting instructions](http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report).

**Comment by rigobcastro** [comment]
@bajtos Thanks for your answer but actually I'm not using more Angular.
